model:
  name: 'EfficentRex'  # or 'RexNet18'
  layers_to_finetune:
    classifier: 5e-3
    features.6: 5e-4
    features.7: 5e-4

training:
  max_epochs: 40
  batch_size: 64
  
num_classes: 8
size: 224