model:
  name: "ViTRex_FullFT"
  warmup_fc_only: true
  layers_to_finetune:
    fc:
      lr: 3e-3
      decay: 0.0001
    backbone:
      lr: 3e-4
      decay: 0.0001

experiment_name: vitrex_fft_b

training:
  max_epochs: 40
  batch_size: 64
  num_workers: 0
  
num_classes: 8
size: 224