model:
  name: 'EfficentRex'  # or 'RexNet18'
  layers_to_finetune:
    classifier: 
      lr: 5e-3
      decay: 0.0001
    features.6: 
      lr: 5e-4
      decay: 0.0001
    features.7:
      lr: 5e-4
      decay: 0.0001

experiment_name: last_block_finetune_weight_decay

training:
  max_epochs: 40
  batch_size: 64
  
num_classes: 8
size: 224