model:
  name: 'RexNet'
  layers_to_finetune: 
    fc: 
      lr: 5e-3
      decay: 0.001
    layer4:
      lr: 5e-4
      decay: 0.01

experiment_name: last_block_finetune_weight_decay

training:
  max_epochs: 40
  batch_size: 64
  
num_classes: 8
size: 224